name: "Release packge to NuGet"

on:
  push:
    tags: [ v* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Pack NuGet
        run: dotnet pack -o nupkg -c Release

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./nupkg
          retention-days: 1
          overwrite: true
          
      - name: Push to Nuget
        run: dotnet nuget push nupkg/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s nuget